# Generated by Django 2.1.4 on 2018-12-10 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='video',
            field=models.CharField(max_length=10000),
        ),
    ]
