# Generated by Django 2.1.4 on 2018-12-18 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_home_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='name',
            field=models.CharField(default='Vidos', max_length=50),
        ),
    ]
